name: Sync RFCs

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install rsync
        run: sudo apt-get install -y rsync
      
      - name: Sync RFCs
        run: |
          mkdir -p rfcs
          rsync -avz --delete rsync.rfc-editor.org::rfcs-text-only/ rfcs/
      
      - name: Update README
        run: |
          {
            echo '# RFC Mirror'
            echo
            echo 'Automatically synchronized mirror of IETF RFCs. This repository is updated daily at midnight UTC.'
            echo
            echo "Last updated: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            echo
            echo '## Recently Published RFCs'
            echo
            echo '| RFC | Title | Date | Status | DOI |'
            echo '|-----|-------|------|--------|-----|'

            awk '
              /^[0-9]{4} / {
                rfc_num=$1
                title_line=substr($0, index($0,$2))
                next_line_num=NR+1
                while (getline && /^[[:space:]]{5,}/) {
                  sub(/^[[:space:]]+/, "", $0)
                  title_line=title_line " " $0
                  next_line_num=NR+1
                }
                date = match(title_line, /[A-Za-z]+ [0-9]{4}/) ? substr(title_line, RSTART, RLENGTH) : "N/A"
                status = match(title_line, /\(Status: ([^)]+)\)/, arr_status) ? arr_status[1] : "UNKNOWN"
                if (match(title_line, /DOI: ([^)]+)/, arr_doi)) {
                  doi = arr_doi[1]
                  doi_text = doi
                  sub(/\/RFC[0-9]+$/, "", doi_text)
                } else {
                  doi = "N/A"
                  doi_text = "N/A"
                }
                title = gensub(/\.\s+[A-Za-z].*$/, "", 1, title_line)
                printf "| [RFC %s](rfcs/rfc%s.txt) | %s | %s | %s | [%s](https://doi.org/%s) |\n", rfc_num, rfc_num, title, date, status, doi_text, doi
                if (NR != next_line_num) { next }
              }
            ' rfcs/rfc-index-latest.txt
          } > README.md || true
      
      - name: Commit and push changes
        run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'GitHub Actions Bot'
          
          git add .
          
          if git diff --staged --quiet; then
            echo 'No changes to commit'
          else
            timestamp=$(date -u +'%Y-%m-%d %H:%M:%S UTC')
            git commit -m "Update RFCs - ${timestamp}"
            git push
          fi 
